Lower MSRV to 1.46.0
Can't go any lower because of error[E0658]: `if` is not allowed in a `const fn`

https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html#const-fn-improvements